/* 🌍 RootLayout.jsx - Define la estructura global de la aplicación */
/* --------------------------------------------------------------- */
/* 📌 Este archivo actúa como la envoltura principal de la app.   
   ✅ Agrega fuentes, estilos globales y metadatos. 
   ✅ Define el HTML y el <body>.
   ✅ Permite layouts persistentes (Navbar, Footer, etc.).
*/


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* 📝 Metadatos globales de la aplicación */
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* 🎨 RootLayout - Envoltura global de la app */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}